name: Sync OneNote to gh-pages

on:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨3點 UTC
  workflow_dispatch: # 手動觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js (Latest)
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install latest onenote2md globally
        run: npm install -g onenote2md

      - name: Run onenote2md
        run: |
          onenote2md -u "https://diagmindtw.com/rawdocx/serve-docx.php?file=" \
                     -b "https://diagmindtw.com/kcms0.php#edit" \
                     -s remote

      - name: Add CNAME for GitHub Pages
        run: echo "docx.diagmindtw.com" > ./output/CNAME

      - name: Add index.html redirect page
        run: |
          cat <<EOF > ./output/index.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="refresh" content="0; url=https://docx.diagmindtw.com/ObstetricsGynecologyDepartment/index.html#2" />
  <title>Redirecting...</title>
</head>
<body>
  <p>Redirecting to <a href="https://docx.diagmindtw.com/ObstetricsGynecologyDepartment/index.html#2">https://docx.diagmindtw.com/ObstetricsGynecologyDepartment/index.html#2</a></p>
</body>
</html>
EOF

      - name: Add redirect pages for each section
        run: |
          mkdir -p ./output/sec
          declare -A redirects=(
            ["2"]="InternalMedicineDepartment"
            ["3"]="SurgicalDepartment"
            ["4"]="ChildDepartment"
            ["5"]="ObstetricsGynecologyDepartment"
            ["6"]="Appointments"
          )

          for key in "${!redirects[@]}"; do
            cat <<EOF > ./output/sec/${key}.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="refresh" content="0; url=https://docx.diagmindtw.com/${redirects[$key]}/index.html" />
  <title>Redirecting...</title>
</head>
<body>
  <p>Redirecting to <a href="https://docx.diagmindtw.com/${redirects[$key]}/index.html">https://docx.diagmindtw.com/${redirects[$key]}/index.html</a></p>
</body>
</html>
EOF
          done

      - name: Deploy ./output to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
